### ISSUE TITLE
Uncompatible With GoLand 2020.2 and 2020.3

### ISSUE THREAD

**Issue by WeiweiGao** [fkorotkov/intellij-thrift#100]
I've tried basically all plugin version, none of it worked, remind me as follows:
Plugin 'Thrift Support' requires plugin 'com.intellij.modules.java' to be installed

**Comment by bogdanovich** [comment]
OK, so I made it work by editing it
vim plugin.jar
select plugin.xml
and update
```
<depends>com.intellij.modules.java</depends>
```
to
```
<depends optional="true">com.intellij.modules.java</depends>
```

**Comment by LiZhenNet** [comment]
I have build it，it work well with  GoLand  2020.3 [thrift.zip](https://github.com/fkorotkov/intellij-thrift/files/5864545/thrift.zip)

**Comment by saturn4er** [comment]
@WeiweiGao already fixed, and already in Marketplace for latest Golands

**Comment by fkorotkov** [comment]
@saturn4er thank you!

**Comment by edwardotis** [comment]
@saturn4er  I do not see this in the MarketPlace for Goland 2020.2.4 ?

**Comment by saturn4er** [comment]
Hi @edwardotis actually, plugin require some features from idea 2020.3. Is it really necessary to use old Goland release?

**Comment by edwardotis** [comment]
@saturn4er Intellij's Bazel plugin has never been updated for 2020.3.x releases of intellij or Goland, so I had reverted to 2020.2.x
However, I just got my project running with Intellij's goland plugin in Intellij 20202.2.x, and the thrift plugin is available. (as well as bazel plugin).
So, I'm all set. Thanks!

**Comment by isopropylcyanide** [comment]
+1 Bazel plugin incompatibility forces us to use `2020.2.x` Goland. Is there a way to make it work for `2020.2`?
