### ISSUE TITLE
Incompatible with IntelliJ 2021.1

### ISSUE THREAD

**Issue by mkasberg** [fkorotkov/intellij-thrift#117]
After upgrading to IntelliJ 2021.1, the plugin is disabled with the message:

> Incompatible: requires IDE build 203.* or older

![image](https://user-images.githubusercontent.com/12214617/113789947-73492d80-96fd-11eb-88c2-f73e0fc0045f.png)

I'm using plugin version 1.8.0, which I believe is the current latest release.

**Comment by fkorotkov** [comment]
Just published 1.9.0 👌
