### ISSUE TITLE
validate top-level type names for uniqueness

### ISSUE THREAD

**Issue by TarasTielkes** [fkorotkov/intellij-thrift#15]
In larger Thrift IDL definitions it happens that you create a top-level type (enum, struct, union, etc) whose name is already used.

The plugin could validate that names of top-level types are unique within the Thrift file.

The Thrift compiler will reject this with an error like the following:

```
[WARNING:C:/work/plq/src/main/resources/outgoing.thrift:214] Duplicate typename UserProfile found in outgoing
[ERROR:C:/work/plq/src/main/resources/outgoing.thrift:214] (last token was 'service')
Type "UserProfile" is already defined.
```

Since this breaks compilation, this should be "red".

**Comment by saturn4er** [comment]
Looks like it's already implemented
