### ISSUE TITLE
WebStorm support

### ISSUE THREAD

**Issue by tematema** [fkorotkov/intellij-thrift#42]
It will be nice to add WebStorm support.

**Comment by bholbrook73** [comment]
+1

**Comment by leaves4j** [comment]
+1

**Comment by andrewtch** [comment]
+1, I suppose, for webstorm / phpstorm support

**Comment by michaelgmiller** [comment]
+1 PyCharm support would be amazing!

**Comment by honorabel** [comment]
See: https://github.com/fkorotkov/intellij-thrift/pull/51

**Comment by fkorotkov** [comment]
Fixed in https://github.com/fkorotkov/intellij-thrift/commit/705a2cde99a3858f2b3f49d91db0ebe53bac1adc

**Comment by fuchao2012** [comment]
it seems not support 2022.1 again : https://plugins.jetbrains.com/plugin/7331-thrift-support

> Not compatible with the version of your running IDE (WebStorm 2022.1)

how can i start a new pr for this support?
