### ISSUE TITLE
Support includes with "../"

### ISSUE THREAD

**Issue by pamalyshev** [fkorotkov/intellij-thrift#48]
For example:
`include "../base.thrift"`
Is highlighted with a message:

> Unresolved include 

And all references to symbols from that include will be marked as:

> Unresolved symbol

However this will be compiled successfully  by standalone  thrift compiler.

**Comment by TakayukiSakai** [comment]
same here...

**Comment by james-johnston-thumbtack** [comment]
Same here as well....

**Comment by groz** [comment]
Fixed locally by reverting 4022916. 
Should I create a revert PR? Not much experience with IntelliJ Plugin SDK, can't tell for sure what that commit was fixing.
