### ISSUE TITLE
No valid translators found

### ISSUE THREAD

**Issue by 10Buns** [fkorotkov/intellij-thrift#49]
Warning:Thrift compiler: No valid translators found for module ThriftDemo. Check facet configuration.

but when  Build/Thrift compiler Test, Apache Thrift Compiler is Found, thrift version 0.10.0

IDEA version: 2016.3.4
Thrift version: 0.10.0
Java version: 1.8.0

**Comment by fkorotkov** [comment]
Please setup Thrift compiler in settings like this:

![image](https://user-images.githubusercontent.com/989066/29839511-53410290-8cb3-11e7-9030-70762a9eff6c.png)
