### ISSUE TITLE
 Does intellij-thrift support in class path thrift including

### ISSUE THREAD

**Issue by chenershuile** [fkorotkov/intellij-thrift#52]
For example, we have A module which has the structure as ：
.
├── main
│   ├── java
│   │   └── com
│   │       └── sankuai
│   │           └── App.java
│   └── resources
│       └── thrift
│           └── cross-module.thrift

Here, in another module B which has A module as a maven dependency , we want to include the cross-module.thrift. 
It is obviously  that if we download this packaged jar of A, extract the cross-module.thrift ,we can achieve the goal. However this can be annoying to handle such a manner since the A module may various and update.
Does intellij-thrift support to include a thrift file in another JAR which it resides in the java class path?

**Comment by fkorotkov** [comment]
You can try manually add includes to includes list in facet's settings for your module. Like this:

![image](https://user-images.githubusercontent.com/989066/29839157-25232d8a-8cb2-11e7-99ac-e149bdb89e73.png)

I need to fix one minor issue before it. Right now includes are not working :-(
