### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by walter-weinmann** [fkorotkov/intellij-thrift#55]
Is there any documentation available how to use this plug-in ?

I did the installation (IntelliJ IDEA 2017.2.2) and see with new project (except the empty project ?) the following:

![image](https://user-images.githubusercontent.com/1956149/29785943-a6128334-8c29-11e7-9dfc-24ec2a1a50da.png)

I also see in the "Project Structure":

![image](https://user-images.githubusercontent.com/1956149/29786430-6d2f444c-8c2b-11e7-9e62-590d95925837.png)

and

![image](https://user-images.githubusercontent.com/1956149/29786088-1e848092-8c2a-11e7-8fdb-622a725061aa.png)

Finally in "Default Settings" I have:

![image](https://user-images.githubusercontent.com/1956149/29786252-bb247628-8c2a-11e7-816c-c863b7549f1c.png)

But I have absolutely no idea how to compile with Thrift or how the formatting of the Thrift file works.

**Comment by xBlackCat** [comment]
Best way to place your *.thrift files to a separate folder in module and mark the folder as 'Source root'
After that you could simply invoke 'rebuild'  command (Ctrl+Shift+F9) on the folder.
Do not forget to specify target lang and folder in Facet configuration of the module - as I noted it is empty in your screenshots.
Also it is preferrable to mark output folder in module for generated files as 'Generated source root'

**Comment by walter-weinmann** [comment]
Thanks a lot for your help !

1. The thrift files are in a separate deirctory:

![image](https://user-images.githubusercontent.com/1956149/29813624-e4129b3e-8caa-11e7-87ff-c60fb633d7a9.png)

2. The folders are marked as follows:

![image](https://user-images.githubusercontent.com/1956149/29813704-2adc420e-8cab-11e7-92ff-594ddc290eb0.png)

3. The facet configuration is as follows:

![image](https://user-images.githubusercontent.com/1956149/29813848-a3aeed80-8cab-11e7-9451-7691c7926100.png)

4. With Ctrl+Shift+F9 I get:

![image](https://user-images.githubusercontent.com/1956149/29814028-3cae151a-8cac-11e7-97e9-b11e2eeca4a3.png)

Ctrl+Shift+F9

![image](https://user-images.githubusercontent.com/1956149/29814006-2550c25a-8cac-11e7-9dd0-db860f171102.png)

**Comment by walter-weinmann** [comment]
I've changed the facets as follows:

![image](https://user-images.githubusercontent.com/1956149/29815038-95f26a9c-8caf-11e7-882e-073150c97e94.png)

but the result of Ctrl+Shift+F9 is the same:

![image](https://user-images.githubusercontent.com/1956149/29815095-c0c569ae-8caf-11e7-9052-404ca99c030c.png)

**Comment by xBlackCat** [comment]
could you attach logs from IDE to the task?

**Comment by walter-weinmann** [comment]
I found the following under `C:\Users\walte\.PyCharmCE2017.2\system\log`:

[threadDump-20170828-152523.txt](https://github.com/fkorotkov/intellij-thrift/files/1260205/threadDump-20170828-152523.txt)

and

[idea.log.txt](https://github.com/fkorotkov/intellij-thrift/files/1260208/idea.log.txt)

(I added the `.txt` extension manually)

**Comment by xBlackCat** [comment]
Do you have any logs in logs/build-log/ folder?

**Comment by walter-weinmann** [comment]
I found the following (again added suffix txt):

[build.log.txt](https://github.com/fkorotkov/intellij-thrift/files/1260287/build.log.txt)

and

[build-log.properties.txt](https://github.com/fkorotkov/intellij-thrift/files/1260290/build-log.properties.txt)

**Comment by xBlackCat** [comment]
Sorry. By mistake Erlang compiler in not worked yet. I've made pull request with fix and it will be working next plugin version.

**Comment by walter-weinmann** [comment]
Thanks a lot - should I try to write a documentation page which describes the IntelliJ configuration (based on the current IntelliJ version) ?

**Comment by xBlackCat** [comment]
U R welcome.

**Comment by walter-weinmann** [comment]
I've started the documentation - @xBlackCat  and @fkorotkov you may contribute directly in my fork.
