### ISSUE TITLE
Version 0.9.7: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils

### ISSUE THREAD

**Issue by walter-weinmann** [fkorotkov/intellij-thrift#57]
Hitting Ctrl+Shift+F9 gives:

![image](https://user-images.githubusercontent.com/1956149/29855195-5f23fcb0-8d4a-11e7-88e2-e2d1f98c724d.png)

Log files:

[build.log.txt](https://github.com/fkorotkov/intellij-thrift/files/1262410/build.log.txt)

and

[build-log.properties.txt](https://github.com/fkorotkov/intellij-thrift/files/1262411/build-log.properties.txt)

**Comment by NikolayMetchev** [comment]
It seems this was supposed to be fixed. However the change either didn't work or it didn't make it into 0.9.7:
https://github.com/fkorotkov/intellij-thrift/issues/54
