### ISSUE TITLE
Attempting to build a project fails with NoClassDefFoundError on IDEA 2019.3 EAP

### ISSUE THREAD

**Issue by chrismiller** [fkorotkov/intellij-thrift#76]
Please see the discussion here for further details:

https://youtrack.jetbrains.net/issue/KT-33899

**Comment by ant-druha** [comment]
https://youtrack.jetbrains.com/issue/IDEA-224829

**Comment by tpasternak** [comment]
I did some investigation of this. It seems it's caused by the calls to `VfsUtil.urlToPath` in `ThriftBuilder.java`. The problem doesn't occur when the strings are replaced with hardcoded values.

```
final String compiler = VfsUtil.urlToPath(thriftConfig.getCompilerPath());
```
```
final String path = VfsUtil.urlToPath(g.getOutputDir());
```
