### ISSUE TITLE
Annotation parsing on unions

### ISSUE THREAD

**Issue by mdhirsch** [fkorotkov/intellij-thrift#88]
My thrift is full of code like
`union SessionInfo {
  1: binary sessionBlob
  2: string sessionBlobHash
}(persisted='true')
`
and intellij shows a parsting error at the '(' saying "'(' unexpected".

If I change the code to
`struct SessionInfo {
  1: binary sessionBlob
  2: string sessionBlobHash
}(persisted='true')
`
Then it all parses right.

**Comment by james-johnston-thumbtack** [comment]
+1 on this issue.  I am also seeing this.  Type annotations are legal on both structures and unions.  The grammar for this is located here:

https://github.com/apache/thrift/blob/2676327f6ea7851459081047c21138e192b0de65/compiler/cpp/src/thrift/thrifty.yy#L665-L688

As best I can tell, the fix to the grammar in this plug-in would involve modifying this union line:

https://github.com/fkorotkov/intellij-thrift/blob/bb9067e2a8f8bd83bfcdb6809a1fa2fd8f65da0d/thrift/src/main/grammar/Thrift.bnf#L103

to have the `TypeAnnotations?` suffix of the existing structure line:

https://github.com/fkorotkov/intellij-thrift/blob/bb9067e2a8f8bd83bfcdb6809a1fa2fd8f65da0d/thrift/src/main/grammar/Thrift.bnf#L98

**Comment by fkorotkov** [comment]
Fixed in #104
